### PR TITLE
Avant dockerfile v2

### PR DESCRIPTION
**Pull request by taylorzr**
[Pivotal #126798591](https://www.pivotaltracker.com/story/show/126798591)

Figured we should just merge this to our master. I don't really see any advantage to having a separate branch. 

Also figured we should just edit Dockerfile instead of having a separate Avant_Dockerfile.

### CODE REVIEW

**Comment by tmertens** [comment]
This is just gonna be super annoying to backmerge every time we want to pull in upstream

**Comment by tmertens** [comment]
That's why i've kept it in a feature branch up to now, it allows us to keep master in sync w/ upstream, we can merge it into our feature branch and if necessary make changes on other branches and merge them into our feature branch rather than master.

**Comment by taylorzr** [comment]
Our fork is our version of this image-builder. So, I think it makes sense to have our master reflect that, and not hide it in a branch. I don't see any advantage to keeping our forks master up to date, if it's not being used in our infrastructure (am I missing something). It's the same level of annoying regardless if in master or a branch, right?

**Comment by tmertens** [comment]
The point of keeping it in a feature branch is that:

- updates from upstream are easier and can be merged into our fork's master in isolation from our changes
- Writing patches for upstream is easier if our fork's master branch is not polluted with non-upstream commits.
- You can simply branch off of our own feature branch to create patches on top of our own customizations.

**Comment by tmertens** [comment]
Just because `master` is generally the default branch for repositories doesn't force us to use it as our primary branch here.

**Pull request closed without merging**
